// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwblutjcoeisfnzjfmac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3Ymx1dGpjb2Vpc2ZuempmbWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MzI2MDYsImV4cCI6MjA3MzMwODYwNn0.4MdsrL977eCx73oBZ4YJal6MLjm7GDRM5jXOL8E1CL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});